{{- range .Values.ingresses }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .certificate.name }}
  namespace: {{ .namespace }}
spec:
  secretName: {{ .certificate.secretName }}
  issuerRef:
    name: {{ .certificate.issuer }}
    kind: ClusterIssuer
  commonName: {{ .fqdn }}
  dnsNames:
  - {{ .fqdn }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .class }}
spec:
  tls:
  - hosts:
    - {{ .fqdn }}
    secretName: {{ .certificate.secretName }}
  rules:
  - host: {{ .fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .service.name }}
            port: 
              number: {{ .service.port }}
{{- end }}