{{- range $index, $stack := .Values.stacks }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $stack.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: {{ $.Values.gitops.repo }}
        revision: {{ $.Values.gitops.revision }}
        directories:
          - path: environments/staging/{{ $stack.name }}/*
  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ default `{{path.basename}}` $stack.namespace }}'
      project: 'default'
      source:
        repoURL: {{ $.Values.gitops.repo }}
        path: '{{ `{{path}}` }}'
        targetRevision: {{ $.Values.gitops.revision }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 30s
        syncOptions:
          - CreateNamespace=false
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
{{- end }}
