{{- if .Values.l2.enabled }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.l2.ipAddressPool.name }}
  namespace: {{ .Values.metallb.namespace }}
spec:
  addresses:
  {{- range .Values.l2.ipAddressPool.addresses }}
    - {{ . }}
  {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2.l2Advertisement.name }}
  namespace: {{ .Values.metallb.namespace }}
{{- end }}