{{- if .Values.l2.enabled }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.l2.ipAddressPool.name }}
  namespace: {{ .Values.l2.ipAddressPool.namespace }}
spec:
  addresses:
  - {{ .Values.l2.ipAddressPool.address }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2.l2Advertisement.name }}
  namespace: {{ .Values.l2.l2Advertisement.namespace }}
{{- end }}