metallb:
  existingConfigMap: metallb-config
  installCRD: true
  namespace: metallb-system
bgp:
  enabled: false
  ipAddressPool:
    name: bgp-pool
    address: 
      - 192.168.100.0/24
    avoidBuggyIPs: true
  bgpPeer:
    name: bgppeer
    myASN: 64521
    peerASN: 64520
    peerAddress: 192.168.10.1
  bgpAdvertisement:
    name: bgpad

l2:
  enabled: false
  ipAddressPool:
    name: l2-pool
    addresses: 
      - 192.168.100.0/24
  l2Advertisement:
    name: l2ad