ingresses:
  - name: ingress-1
    namespace: namespace-1
    class: nginx
    fqdn: ingress-1.example.com
    service:
      name: service
      port: 80
    certificate:
      name: ingress-1-cert
      secretName: ingress-1-cert
      issuer: letsencrypt-stag
  - name: ingress-2
    namespace: namespace-2
    class: nginx
    fqdn: ingress-2.example.com
    service:
      name: service
      port: 80
    certificate:
      name: ingress-2-cert
      secretName: ingress-2-cert
      issuer: letsencrypt-stag
