fqdn: ingress-domain.example.com
namespace: ingress
ingress:
  name: ingress-domain
  class: nginx
service:
  name: ingress-domain-svc
  namespace: ingress-domain-svc-namespace
  port: 80
certificate:
  name: ingress-domain-cert
  issuer: letsencrypt-stag
