ingress-nginx:
  crds:
    create: true
  controller:
    replicaCount: 3
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
    admissionWebhooks:
      enabled: false
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false